version: '2'
services:
  app:
    image: race-base-image
    volumes:
      - ./:/go/src/app/
    working_dir: /go/src/app/
    command: go run main.go
  dep:
    image: race-base-image
    volumes:
    - ./:/go/src/app
    working_dir: /go/src/app
    command: dep ensure -v
  unit:
    image: race-base-image
    volumes:
      - ./:/go/src/app/
    working_dir: /go/src/app/
    command: sh -c "go test -v $$(go list ./... | grep -v /vendor/)"